name: Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate-nix:
    name: Validate Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix flake check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix develop -c cabal update
      - run: nix develop -c cabal freeze
      - uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: cabal-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      - run: nix develop -c cabal build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix develop -c cabal update
      - run: nix develop -c cabal freeze
      - uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: cabal-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      - run: nix develop -c cabal test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix develop -c hlint lib src docs-ts test
