name: Publish

on:
  create:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  publish:
    name: Publish binaries
    strategy:
      matrix:
        os:
          [
            { name: "linux", runner: "ubuntu-latest" },
            { name: "macos", runner: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v3
      # Using Nix causes dynamic linking issues on macOS. It's easier to
      # workaround on Linux with patchelf at least. (Yes, building statically
      # would be substantially better.)
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: 9.2.7
      - run: cabal freeze
      - uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: cabal-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      - name: Build
        run: cabal install --install-method=copy --installdir=dist
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/tshm
          asset_name: tshm-${{ github.ref_name }}-${{ matrix.os.name }}-x86_64
          tag: ${{ github.ref }}
